### ISSUE TITLE
Omit fields

### ISSUE THREAD

**Issue by mcosti** [crysxd/SharedFirebasePreferences#1]
Hey there. I'm suprised this repo is not so popular, it's simply awesome!

However, I did have some problems with java.lang.Long cannot be cast to java.lang.Integer. I solved them with some internal castings (pretty ugly), but now I want to use it with a preference from a gradle repo, but I cannot modify it(so easily) and I don't really need it in firebase either.

It would be nice if we could omit some fields on the sync. Thank you!

**Comment by crysxd** [comment]
Hey,
happy you like this project :)

Can you give me a stack trace of the casting issue?

About the fields: Does the lib use the same Prefernces as you? Usually a library would use a separate preference instance which would not be synced automatically. How does the library get a instance of the SharedFirebasePreferences?

**Comment by mcosti** [comment]
Right now I can't write the stack trace, but here is the one I tried to use:
[https://github.com/yukuku/ambilwarna](https://github.com/yukuku/ambilwarna)
I think it's synced with the default shared preferences.

**Comment by crysxd** [comment]
I took a look into the linked library. If I understand you correctly, you let the user enter a color in your preferences? The library is a preference to be used with PreferenceFragment/PreferenceActivity. In this case the property will be stored in the default shared preferences. 
I don't understand why you do not want this preference to be synced as your users would be disappointed when they have to enter the same color again after re-installing your app?

Nevertheless, I can added a method to blacklist certain keys for you.

**Comment by crysxd** [comment]
Added with 1.0.1, see https://github.com/crysxd/shared-firebase-preferences#omit-values
